/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/availability-exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminAvailabilityExceptions_list"];
        put?: never;
        post: operations["AdminAvailabilityExceptions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/availability-exceptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminAvailabilityExceptions_read"];
        put?: never;
        post?: never;
        delete: operations["AdminAvailabilityExceptions_remove"];
        options?: never;
        head?: never;
        patch: operations["AdminAvailabilityExceptions_update"];
        trace?: never;
    };
    "/admin/availability-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminAvailabilityRules_list"];
        put?: never;
        post: operations["AdminAvailabilityRules_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/availability-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminAvailabilityRules_read"];
        put?: never;
        post?: never;
        delete: operations["AdminAvailabilityRules_remove"];
        options?: never;
        head?: never;
        patch: operations["AdminAvailabilityRules_update"];
        trace?: never;
    };
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список бронирований с фильтрами по дате и типу события (FR-9). */
        get: operations["AdminBookings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminBookings_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Изменение статуса брони (FR-10).
         *     При установке статуса `cancelled` слот автоматически освобождается (BR-7).
         */
        patch: operations["AdminBookings_updateStatus"];
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список всех типов событий, включая неактивные. */
        get: operations["AdminEventTypes_list"];
        put?: never;
        post: operations["AdminEventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminEventTypes_read"];
        put?: never;
        post?: never;
        delete: operations["AdminEventTypes_remove"];
        options?: never;
        head?: never;
        patch: operations["AdminEventTypes_update"];
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Создание брони на один или несколько последовательных слотов одного типа события (FR-12).
         *     Бэкенд проверяет лимит 2 часа на гостя (BR-1), последовательность слотов (D-7),
         *     занятость (BR-2) и попадание в периоды доступности (BR-3).
         */
        post: operations["PublicBookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/closed-dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список дат-исключений (полностью или частично закрытых) в горизонте бронирования. */
        get: operations["PublicClosedDates_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список активных типов событий, доступных для бронирования. */
        get: operations["PublicEventTypes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guest-bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Брони гостя (по email) на конкретную дату — для предзаполнения и клиентской проверки лимита/последовательности. */
        get: operations["PublicGuestBookings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Сырые слоты доступности на конкретную дату для конкретного типа события.
         *     Возвращает 404, если дата закрыта по исключению (FR-14, D-6).
         */
        get: operations["PublicSlots_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Бронь — полное представление для администратора (FR-9). */
        AdminBooking: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            event_type_id: number;
            guest: components["schemas"]["Guest"];
            /** @description Идентификатор группы брони, если бронь — часть длинной последовательной брони (FR-12). */
            booking_group_id: string | null;
            date: components["schemas"]["CalendarDate"];
            start: components["schemas"]["TimeOfDay"];
            end: components["schemas"]["TimeOfDay"];
            comment: string | null;
            status: components["schemas"]["BookingStatus"];
        };
        AdminBookingListResponse: {
            bookings: components["schemas"]["AdminBooking"][];
        };
        /** @description Тип события — полное представление для администратора (включает неактивные). */
        AdminEventType: {
            /** Format: int32 */
            id: number;
            name: string;
            description: string | null;
            /** @enum {number} */
            duration_minutes: 15 | 30;
            color: string;
            is_active: boolean;
        };
        /**
         * @description Единый формат ошибки для всего API.
         *     Формат в стиле Laravel (`message` + `errors`), дополненный
         *     машиночитаемым `code` на верхнем уровне.
         */
        ApiError: {
            /** @description Машиночитаемый код ошибки. */
            code: components["schemas"]["ErrorCode"];
            /** @description Человекочитаемое сообщение об ошибке. */
            message: string;
            /**
             * @description Ошибки валидации по полям (как в Laravel):
             *     ключ — имя поля, значение — список сообщений.
             *     Присутствует только при `code = VALIDATION_ERROR`.
             */
            errors?: {
                [key: string]: string[];
            };
        };
        /** @description Исключение из регулярной доступности — выходной день или частичное закрытие (FR-8). */
        AvailabilityException: {
            /** Format: int32 */
            id: number;
            date: components["schemas"]["CalendarDate"];
            is_closed: boolean;
            start_time: components["schemas"]["TimeOfDay"] | null;
            end_time: components["schemas"]["TimeOfDay"] | null;
        };
        /** @description Регулярный интервал доступности по дню недели (FR-8). */
        AvailabilityRule: {
            /** Format: int32 */
            id: number;
            /**
             * Format: int32
             * @description День недели: 0 (воскресенье) — 6 (суббота).
             */
            weekday: number;
            start_time: components["schemas"]["TimeOfDay"];
            end_time: components["schemas"]["TimeOfDay"];
        };
        /** @description Один слот в составе запроса на бронирование. */
        BookingSlotInput: {
            /** @description Начало слота, "HH:mm". */
            start: components["schemas"]["TimeOfDay"];
        };
        /**
         * @description Статус брони.
         * @enum {string}
         */
        BookingStatus: "pending" | "confirmed" | "cancelled";
        /**
         * Format: date
         * @description Дата в формате "YYYY-MM-DD" (naive, без часового пояса; подразумевается Europe/Moscow).
         */
        CalendarDate: string;
        /** @description Дата, закрытая для бронирования (полностью или частично) — availability exception. */
        ClosedDate: {
            date: components["schemas"]["CalendarDate"];
            is_closed: boolean;
            /** @description Начало интервала-исключения, если закрытие частичное (не весь день). */
            start_time: components["schemas"]["TimeOfDay"] | null;
            /** @description Конец интервала-исключения, если закрытие частичное. */
            end_time: components["schemas"]["TimeOfDay"] | null;
        };
        ClosedDatesResponse: {
            dates: components["schemas"]["ClosedDate"][];
        };
        CreateAvailabilityExceptionRequest: {
            date: components["schemas"]["CalendarDate"];
            is_closed: boolean;
            start_time?: components["schemas"]["TimeOfDay"] | null;
            end_time?: components["schemas"]["TimeOfDay"] | null;
        };
        CreateAvailabilityRuleRequest: {
            /** Format: int32 */
            weekday: number;
            start_time: components["schemas"]["TimeOfDay"];
            end_time: components["schemas"]["TimeOfDay"];
        };
        /**
         * @description Тело запроса на создание брони.
         *     Может содержать несколько последовательных слотов одного типа события (FR-12, D-7).
         */
        CreateBookingRequest: {
            /** Format: int32 */
            event_type_id: number;
            date: components["schemas"]["CalendarDate"];
            guest: components["schemas"]["GuestInput"];
            slots: components["schemas"]["BookingSlotInput"][];
        };
        /** @description Ответ при успешном создании брони(й). */
        CreateBookingResponse: {
            /** @description Идентификатор группы брони, объединяющий все слоты одной операции (FR-12). */
            booking_group_id: string;
            status: components["schemas"]["BookingStatus"];
        };
        CreateEventTypeRequest: {
            name: string;
            description?: string | null;
            /** @enum {number} */
            duration_minutes: 15 | 30;
            color: string;
            /** @default true */
            is_active: boolean;
        };
        /**
         * @description Машиночитаемые коды бизнес-ошибок.
         * @enum {string}
         */
        ErrorCode: "LIMIT_EXCEEDED" | "SLOT_NOT_SEQUENTIAL" | "SLOT_TAKEN" | "SLOT_UNAVAILABLE" | "DATE_OUT_OF_RANGE" | "NOT_FOUND" | "VALIDATION_ERROR";
        /** @description Тип события, доступный для бронирования (публичное представление). */
        EventType: {
            /** Format: int32 */
            id: number;
            name: string;
            description: string | null;
            /**
             * @description Длительность одного слота в минутах: 15 или 30 (BR-5).
             * @enum {number}
             */
            duration_minutes: 15 | 30;
            /** @description Цвет для отображения в календаре (например, HEX). */
            color: string;
        };
        /** @description Гость — идентифицируется по email (D-1). */
        Guest: {
            /** Format: int32 */
            id: number;
            email: string;
            name: string;
            phone: string;
        };
        /** @description Одна бронь гостя (для отображения "моих" броней в рамках дня). */
        GuestBookingItem: {
            status: components["schemas"]["BookingStatus"];
            /** @description Начало забронированного слота, "HH:mm". */
            start: components["schemas"]["TimeOfDay"];
            /** @description Конец забронированного слота, "HH:mm". */
            end: components["schemas"]["TimeOfDay"];
        };
        /** @description Ответ со списком броней гостя за указанную дату (идентификация по email). */
        GuestBookingsResponse: {
            date: components["schemas"]["CalendarDate"];
            bookings: components["schemas"]["GuestBookingItem"][];
        };
        /** @description Данные гостя, передаваемые при оформлении брони. */
        GuestInput: {
            name: string;
            /** Format: email */
            email: string;
            /** @description Телефон в российском формате `+7 (XXX) XXX-XX-XX`; формат проверяется бизнес-логикой, не схемой. */
            phone: string;
            comment?: string | null;
        };
        NotFoundError: {
            /** @enum {string} */
            code: "NOT_FOUND";
            message: string;
        };
        /** @description Один слот в сетке доступности. Не содержит персональных данных гостей. */
        Slot: {
            /** @description Начало слота, "HH:mm". */
            start: components["schemas"]["TimeOfDay"];
            /** @description Конец слота, "HH:mm". */
            end: components["schemas"]["TimeOfDay"];
            status: components["schemas"]["SlotStatus"];
        };
        /**
         * @description Статус слота в общей сетке доступности.
         *     Видим всем без исключений персональных данных.
         * @enum {string}
         */
        SlotStatus: "free" | "pending" | "confirmed";
        /** @description Ответ со списком слотов доступности на конкретную дату для конкретного типа события. */
        SlotsResponse: {
            date: components["schemas"]["CalendarDate"];
            /** Format: int32 */
            event_type_id: number;
            slots: components["schemas"]["Slot"][];
        };
        /** @description Время слота в формате "HH:mm" (naive, без часового пояса; подразумевается Europe/Moscow). */
        TimeOfDay: string;
        UpdateAvailabilityExceptionRequest: {
            date?: components["schemas"]["CalendarDate"];
            is_closed?: boolean;
            start_time?: components["schemas"]["TimeOfDay"] | null;
            end_time?: components["schemas"]["TimeOfDay"] | null;
        };
        UpdateAvailabilityRuleRequest: {
            /** Format: int32 */
            weekday?: number;
            start_time?: components["schemas"]["TimeOfDay"];
            end_time?: components["schemas"]["TimeOfDay"];
        };
        /** @description Запрос на изменение статуса брони администратором (FR-10). Отмена/отклонение освобождает слот (BR-7). */
        UpdateBookingStatusRequest: {
            status?: components["schemas"]["BookingStatus"];
        };
        UpdateEventTypeRequest: {
            name?: string;
            description?: string | null;
            /** @enum {number} */
            duration_minutes?: 15 | 30;
            color?: string;
            is_active?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminAvailabilityExceptions_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityException"][];
                };
            };
        };
    };
    AdminAvailabilityExceptions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAvailabilityExceptionRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityException"];
                };
            };
        };
    };
    AdminAvailabilityExceptions_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityException"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    AdminAvailabilityExceptions_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    AdminAvailabilityExceptions_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAvailabilityExceptionRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityException"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    AdminAvailabilityRules_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityRule"][];
                };
            };
        };
    };
    AdminAvailabilityRules_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAvailabilityRuleRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityRule"];
                };
            };
        };
    };
    AdminAvailabilityRules_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityRule"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    AdminAvailabilityRules_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    AdminAvailabilityRules_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAvailabilityRuleRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityRule"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    AdminBookings_list: {
        parameters: {
            query?: {
                date?: components["schemas"]["CalendarDate"];
                event_type_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBookingListResponse"];
                };
            };
        };
    };
    AdminBookings_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBooking"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    AdminBookings_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBookingStatusRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBooking"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    AdminEventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventType"][];
                };
            };
        };
    };
    AdminEventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventType"];
                };
            };
        };
    };
    AdminEventTypes_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventType"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    AdminEventTypes_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    AdminEventTypes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventType"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    PublicBookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateBookingResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    PublicClosedDates_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosedDatesResponse"];
                };
            };
        };
    };
    PublicEventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    PublicGuestBookings_list: {
        parameters: {
            query: {
                email: string;
                date: components["schemas"]["CalendarDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestBookingsResponse"];
                };
            };
        };
    };
    PublicSlots_list: {
        parameters: {
            query: {
                event_type_id: number;
                date: components["schemas"]["CalendarDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
}
